### ISSUE TITLE
Status/examples/tests?

### ISSUE THREAD

**Issue by fullofcaffeine** [cambiata/HxLazy#1]
Hi!

Interested to know the status of this lib. I'm currently doing some research on lazy evaluation / generators applied to Haxe and found it. Have you ever used it? If so, do you have any examples of it in action? 

Cheers!

**Comment by cambiata** [comment]
Hi Marcelo!

This is just a simple "memoizing" solution that in some cases can speed things up by storing the result from (costly) calculations as a private variable, and further on read result from that. It has nothing to do with lazy evalutaion in iterators/generators. Unf I have no experience in that kind of stuff...
